Repository ImMin5/barrier-free, pull requests merged in 2022-04, with the labels that each got.

#5 [DOCS] Edit gitignore
  .gitignore
  src/main/webapp/WEB-INF/views/home.jsp
Labels: documentation

#6 SET open api key value at ApiController.java from application.yml
  .gitignore
  bin/main/application-dev.yml
  bin/main/application.properties
  bin/main/application.yml
  src/main/java/com/team/bf/HomeController.java
  src/main/java/com/team/bf/controller/ApiController.java
  src/main/resources/application-dev.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: enhancement

#30 로고 이미지 수정
  src/main/webapp/img/bf_logo-01.png
  src/main/webapp/img/bf_logo-01.svg
  src/main/webapp/img/bf_logo-02.png
  src/main/webapp/img/bf_logo-02.svg
  src/main/webapp/img/bf_logo-03.png
  src/main/webapp/img/bf_logo-03.svg
Labels: documentation

#34 Open Ap Controller 수정
  src/main/java/com/team/bf/HomeController.java
  src/main/java/com/team/bf/controller/AccommodationController.java
  src/main/java/com/team/bf/controller/ApiController.java
  src/main/java/com/team/bf/controller/MapAndPlannerController.java
  src/main/java/com/team/bf/controller/MemberController.java
  src/main/java/com/team/bf/controller/TourLocationController.java
  src/main/java/com/team/bf/service/OpenApiService.java
  src/main/webapp/WEB-INF/views/accommodation/accommodationPage.jsp
Labels: enhancement

#46 [FEAT]bottom CSS수정
  src/main/webapp/WEB-INF/inc/bottom.jsp
  src/main/webapp/css/bottom.css
Labels: enhancement

#44 공지/문의사항 생성,조회,추가,삭제 기능 작성 close #33
  src/main/java/com/team/bf/HomeController.java
  src/main/java/com/team/bf/controller/BoardController.java
  src/main/java/com/team/bf/controller/MapAndPlannerController.java
  src/main/java/com/team/bf/controller/MemberController.java
  src/main/java/com/team/bf/controller/TourLocationController.java
  src/main/java/com/team/bf/dao/BoardDAO.java
  src/main/java/com/team/bf/service/BoardService.java
  src/main/java/com/team/bf/service/BoardServiceImpl.java
  src/main/java/com/team/bf/service/OpenApiService.java
  src/main/java/com/team/bf/vo/BoardVO.java
  src/main/java/com/team/bf/vo/PagingVO.java
  src/main/resources/mapper/boardMapper.xml
  src/main/resources/mapper/memberMapper.xml
Labels: enhancement

#49 [FEAT]bottom CSS수정
  src/main/webapp/WEB-INF/inc/bottom.jsp
  src/main/webapp/css/bottom.css
Labels: enhancement

#52 리뷰 CRUD기능 작성
  src/main/java/com/team/bf/controller/BoardController.java
  src/main/java/com/team/bf/controller/MemberController.java
  src/main/java/com/team/bf/controller/ReviewController.java
  src/main/java/com/team/bf/dao/ReviewDAO.java
  src/main/java/com/team/bf/service/ReviewService.java
  src/main/java/com/team/bf/vo/ReviewVO.java
  src/main/resources/mapper/reviewMapper.xml
Labels: enhancement

#56 [FEAT] OpenApiService detailCommon 파라미터 변경 및 로직 수정 close #55
  src/main/java/com/team/bf/controller/MapAndPlannerController.java
  src/main/java/com/team/bf/dao/ReviewDAO.java
  src/main/java/com/team/bf/service/OpenApiService.java
  src/main/java/com/team/bf/service/ReviewService.java
  src/main/resources/mapper/reviewMapper.xml
Labels: enhancement

#58 map뷰 수정
  src/main/webapp/WEB-INF/views/map/mapView.jsp
  src/main/webapp/css/mapstyle.css
Labels: enhancement

#62 소개페이지 생성 close #63
  src/main/webapp/WEB-INF/views/accommodation/accommodationPage.jsp
  src/main/webapp/WEB-INF/views/introduction.jsp
  src/main/webapp/WEB-INF/views/travel_information/travel_informationPage.jsp
  src/main/webapp/css/introductionstyle.css
  src/main/webapp/img/introduction/introbackground2.jpg
  src/main/webapp/img/introduction/introimg1.jpg
  src/main/webapp/img/introduction/introimg2.jpg
  src/main/webapp/img/introduction/introimg3.jpg
Labels: enhancement

#61 [FIX] 비밀번호 찾기 버그 수정 #59
  src/main/webapp/WEB-INF/views/member/password.jsp
  src/main/webapp/WEB-INF/views/member/signupView.jsp
Labels: documentation

#74 mypage url중복선언 수정 및 mapView.jsp에 hompage 데이터 추가
  src/main/java/com/team/bf/controller/BoardController.java
  src/main/java/com/team/bf/controller/MapAndPlannerController.java
Labels: bug, enhancement

#75 boardMapper.xml->boardAndReplySelectAll에 select userid 추가 및 공지사항 close #70
  src/main/resources/mapper/boardMapper.xml
Labels: bug

#76 OpenApiService 지역코드 조회 기능 추가
  src/main/java/com/team/bf/controller/AccommodationController.java
  src/main/java/com/team/bf/service/OpenApiService.java
Labels: enhancement

#83 [FEAT]문의/공지사항 수정
  src/main/java/com/team/bf/controller/BoardController.java
  src/main/webapp/WEB-INF/views/community/board.jsp
  src/main/webapp/WEB-INF/views/community/boardDetail.jsp
  src/main/webapp/WEB-INF/views/community/boardEdit.jsp
  src/main/webapp/WEB-INF/views/community/boardForm.jsp
Labels: enhancement

#86 MapAndPlannerController에서 reviewCount수정, 평점으로 뜨게 수정
  src/main/java/com/team/bf/controller/MapAndPlannerController.java
  src/main/java/com/team/bf/dao/PlannerDAO.java
  src/main/java/com/team/bf/service/PlannerService.java
  src/main/java/com/team/bf/service/PlannerServiceImpl.java
  src/main/java/com/team/bf/vo/PlannerLocationVO.java
  src/main/java/com/team/bf/vo/PlannerMemberVO.java
  src/main/java/com/team/bf/vo/PlannerVO.java
  src/main/resources/mapper/plannerMapper.xml
Labels: bug

#85 reivewMapper 타입지정 오류 수정 close #84
  src/main/java/com/team/bf/controller/ReviewController.java
  src/main/resources/mapper/reviewMapper.xml
Labels: bug

#87 boardMapper.xml selectByNo에서 content 데이터 추가 및 페이지 연결
  src/main/java/com/team/bf/controller/BoardController.java
  src/main/java/com/team/bf/controller/MemberController.java
  src/main/resources/mapper/boardMapper.xml
Labels: bug

#91 마이페이에지 뷰에 유저정보 데이터 객체 mvo추가 close #88
  src/main/java/com/team/bf/controller/BoardController.java
  src/main/java/com/team/bf/controller/MemberController.java
Labels: bug, enhancement

#92 [FEAT]map 검색기능 추가
  src/main/webapp/WEB-INF/views/map/mapView.jsp
  src/main/webapp/css/mapstyle.css
Labels: enhancement

#93 건의사항 CRUD 기능 추가
  src/main/java/com/team/bf/controller/SuggestionController.java
  src/main/java/com/team/bf/dao/SuggestionDAO.java
  src/main/java/com/team/bf/service/SuggestionService.java
  src/main/java/com/team/bf/service/SuggestionServiceImpl.java
  src/main/java/com/team/bf/vo/SuggestionVO.java
  src/main/resources/mapper/suggestionMapper.xml
Labels: bug, enhancement

#97 [FEAT]공지/문의사항 게시글 수정/삭제
  src/main/webapp/WEB-INF/views/community/board.jsp
  src/main/webapp/WEB-INF/views/community/boardDetail.jsp
  src/main/webapp/WEB-INF/views/community/boardEdit.jsp
  src/main/webapp/WEB-INF/views/community/boardForm.jsp
Labels: enhancement

#99 [FEAT]top, bottom, main 링크 연결 및 css수정
  src/main/webapp/WEB-INF/inc/bottom.jsp
  src/main/webapp/WEB-INF/inc/top.jsp
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/css/bottom.css
  src/main/webapp/css/home.css
  src/main/webapp/css/top.css
Labels: enhancement

#101 Board controller 중복 맵핑 수정 close #100
  src/main/java/com/team/bf/controller/BoardController.java
Labels: bug

#90 여행플랜 수정,삭제, 조회기능 추가 close#77
  src/main/java/com/team/bf/controller/MapAndPlannerController.java
  src/main/java/com/team/bf/dao/PlannerDAO.java
  src/main/java/com/team/bf/service/PlannerService.java
  src/main/java/com/team/bf/service/PlannerServiceImpl.java
  src/main/java/com/team/bf/vo/PlannerVO.java
  src/main/java/com/team/bf/vo/ResponseVO.java
  src/main/resources/mapper/memberMapper.xml
  src/main/resources/mapper/plannerMapper.xml
Labels: enhancement

#102 로그인 회원가입 후 처리 변경 및 마이페이지 문의사항 연결
  src/main/java/com/team/bf/controller/MemberController.java
Labels: enhancement

#103 마이페이지의 건의사항 뷰페이지 연결
  src/main/java/com/team/bf/controller/BoardController.java
  src/main/java/com/team/bf/dao/BoardDAO.java
  src/main/java/com/team/bf/service/BoardService.java
  src/main/java/com/team/bf/service/BoardServiceImpl.java
  src/main/resources/mapper/boardMapper.xml
Labels: enhancement

#112 [FEAT]map뷰 오버레이 기능 구현, plan 부분 레이아웃 추가, plan뷰를 비동기로 만듦
  src/main/webapp/WEB-INF/views/map/mapView.jsp
  src/main/webapp/css/mapstyle.css
Labels: enhancement

#116 ReviewVO에 title 추가 close #111
  src/main/java/com/team/bf/vo/ReviewVO.java
  src/main/resources/mapper/reviewMapper.xml
Labels: documentation

#115 mapView 통신에러
  src/main/java/com/team/bf/controller/MapAndPlannerController.java
  src/main/java/com/team/bf/service/OpenApiService.java
  src/main/webapp/WEB-INF/views/map/mapView.jsp
Labels: enhancement

#117 [FEAT]공지/문의사항 수정
  src/main/webapp/WEB-INF/inc/top.jsp
  src/main/webapp/WEB-INF/views/community/board.jsp
  src/main/webapp/WEB-INF/views/community/boardDetail.jsp
  src/main/webapp/WEB-INF/views/community/boardEdit.jsp
  src/main/webapp/WEB-INF/views/community/boardForm.jsp
  src/main/webapp/css/board.css
Labels: enhancement

#118 mypage 나의 플래너 Controller 연결
  src/main/java/com/team/bf/controller/MapAndPlannerController.java
  src/main/java/com/team/bf/controller/MemberController.java
  src/main/resources/mapper/memberMapper.xml
Labels: documentation

#119 myplan 중복 맵핑 삭제
  src/main/java/com/team/bf/controller/BoardController.java
  src/main/java/com/team/bf/controller/MapAndPlannerController.java
  src/main/java/com/team/bf/controller/MemberController.java
  src/main/java/com/team/bf/dao/BoardDAO.java
  src/main/java/com/team/bf/service/BoardService.java
  src/main/java/com/team/bf/service/BoardServiceImpl.java
  src/main/java/com/team/bf/service/OpenApiService.java
  src/main/resources/mapper/boardMapper.xml
  src/main/webapp/WEB-INF/views/map/mapView.jsp
  src/main/webapp/WEB-INF/views/map/mapView2.jsp
  src/main/webapp/WEB-INF/views/plan/planView.jsp
Labels: documentation

#120 문의사항 뷰 Controller 재연결 및 페이지네이션 기능 추가
  src/main/java/com/team/bf/controller/BoardController.java
  src/main/java/com/team/bf/dao/BoardDAO.java
  src/main/java/com/team/bf/service/BoardService.java
  src/main/java/com/team/bf/service/BoardServiceImpl.java
  src/main/resources/mapper/boardMapper.xml
Labels: enhancement

#122 마이페이지->나의 리뷰 페이지네이션 및 검색 기능 추가
  src/main/java/com/team/bf/controller/ReviewController.java
  src/main/java/com/team/bf/dao/ReviewDAO.java
  src/main/java/com/team/bf/service/ReviewService.java
  src/main/java/com/team/bf/vo/PagingVO.java
  src/main/resources/mapper/reviewMapper.xml
Labels: enhancement

#123 mypage 나의 플래너 url 수정
  src/main/java/com/team/bf/controller/MapAndPlannerController.java
Labels: enhancement

#124 회원정보 업데이트 기능 추가 close #104
  src/main/java/com/team/bf/controller/MemberController.java
  src/main/java/com/team/bf/dao/MemberDAO.java
  src/main/java/com/team/bf/service/MemberService.java
  src/main/java/com/team/bf/service/MemberServiceImpl.java
  src/main/resources/mapper/memberMapper.xml
Labels: enhancement

#126 mypage 나의 건의사항 답변과 함께 불러오기 기능 추가 close #106
  src/main/java/com/team/bf/controller/BoardController.java
  src/main/resources/mapper/boardMapper.xml
Labels: enhancement

#131 숙박정보 리스트뷰, 상세 뷰 데이터 전달
  src/main/java/com/team/bf/controller/AccommodationController.java
  src/main/java/com/team/bf/service/OpenApiService.java
Labels: documentation, enhancement

#132 여행지 정보 뷰 연결 및 데이터 전송 기능 추가 close #127
  src/main/java/com/team/bf/controller/AccommodationController.java
  src/main/java/com/team/bf/controller/TourLocationController.java
  src/main/java/com/team/bf/dao/ReviewDAO.java
  src/main/java/com/team/bf/service/OpenApiService.java
  src/main/java/com/team/bf/service/ReviewService.java
  src/main/resources/mapper/reviewMapper.xml
  src/main/webapp/WEB-INF/views/travel_information/travel_informationPage.jsp
Labels: documentation, enhancement

#133 ReviewController -> myreview에 pvo객체 추가
  src/main/java/com/team/bf/controller/ReviewController.java
Labels: bug

#105 회원탈퇴, 나의 리뷰, 리뷰 삭제 추가
  src/main/webapp/WEB-INF/views/community/suggest.jsp
  src/main/webapp/WEB-INF/views/community/suggestWrite.jsp
  src/main/webapp/WEB-INF/views/mypage/delete.jsp
  src/main/webapp/WEB-INF/views/mypage/memberEdit.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage.jsp
  src/main/webapp/WEB-INF/views/mypage/myplan.jsp
  src/main/webapp/WEB-INF/views/mypage/myqna.jsp
  src/main/webapp/WEB-INF/views/mypage/myreview.jsp
  src/main/webapp/css/delete.css
  src/main/webapp/css/mypage.css
  src/main/webapp/css/myplanner.css
  src/main/webapp/css/myqna.css
  src/main/webapp/css/myreview.css
  src/main/webapp/css/suggest.css
  src/main/webapp/img/member/bf_logo_delete.png
Labels: enhancement

#134 admin 로그인 페이지, 공지/문의사항 페이지 연결
  src/main/java/com/team/bf/controller/AdminController.java
  src/main/java/com/team/bf/dao/MemberDAO.java
  src/main/java/com/team/bf/service/MemberService.java
  src/main/java/com/team/bf/service/MemberServiceImpl.java
  src/main/resources/mapper/memberMapper.xml
  src/main/webapp/WEB-INF/views/admin/board.jsp
  src/main/webapp/WEB-INF/views/admin/login.jsp
Labels: bug

#136 [FEAT]plan 레이아웃 구현
  src/main/webapp/WEB-INF/views/map/mapView.jsp
  src/main/webapp/css/mapstyle.css
  src/main/webapp/img/map/map_30.png
Labels: enhancement

#137 [FEAT]보드 버튼 수정 및 코디네이터 뷰 작성
  src/main/webapp/WEB-INF/coordinator/coordinator.jsp
  src/main/webapp/WEB-INF/views/community/boardDetail.jsp
  src/main/webapp/WEB-INF/views/community/boardEdit.jsp
  src/main/webapp/WEB-INF/views/community/boardForm.jsp
  src/main/webapp/WEB-INF/views/coordinator/coordinator.jsp
  src/main/webapp/WEB-INF/views/coordinator/coordinatorForm.jsp
Labels: enhancement

#140 관리자 로그인 후 페이지 이동 안됨 수정
  src/main/java/com/team/bf/controller/AdminController.java
  src/main/webapp/WEB-INF/views/admin/board.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage.jsp
Labels: bug

#143 나의 리뷰, 문의사항에 PaginVO 데이터 추가 close #138
  src/main/java/com/team/bf/controller/BoardController.java
  src/main/java/com/team/bf/controller/ReviewController.java
Labels: bug

#146 [FEAT] 여행, 숙박정보 리뷰 없을 시 리뷰 정보 전달 안됨
  src/main/java/com/team/bf/controller/AccommodationController.java
  src/main/java/com/team/bf/controller/TourLocationController.java
Labels: enhancement

#148 [STYLE] 마이페이지 리뷰, 문의사항 default pageCount 변경
  src/main/java/com/team/bf/controller/BoardController.java
  src/main/java/com/team/bf/controller/ReviewController.java
Labels: enhancement

#149 숙박정보페이지, 여행정보페이지 API데이터 적용 및 스타일 수정
  src/main/webapp/WEB-INF/views/accommodation/accommodationPage.jsp
  src/main/webapp/WEB-INF/views/travel_information/travel_informationPage.jsp
  src/main/webapp/css/accommodationstyle.css
  src/main/webapp/css/introductionstyle.css
  src/main/webapp/img/pictogram/search_box_icon.png
  src/main/webapp/img/pictogram/search_box_icon_on.png
Labels: enhancement

#152 [FEAT] 문의사항 답변 상세뷰기 뷰 연결
  src/main/java/com/team/bf/controller/BoardController.java
  src/main/java/com/team/bf/dao/BoardDAO.java
  src/main/java/com/team/bf/service/BoardService.java
  src/main/java/com/team/bf/service/BoardServiceImpl.java
  src/main/resources/mapper/boardMapper.xml
Labels: enhancement

#153 소개페이지 CSS수정
  src/main/webapp/css/introductionstyle.css
Labels: bug

#154 [FEAT]관리자페이지생성, 탑, 바텀 수정
  src/main/webapp/WEB-INF/inc/top.jsp
  src/main/webapp/WEB-INF/views/admin/board.jsp
  src/main/webapp/WEB-INF/views/community/board.jsp
  src/main/webapp/WEB-INF/views/community/boardDetail.jsp
  src/main/webapp/WEB-INF/views/community/boardForm.jsp
  src/main/webapp/WEB-INF/views/coordinator/coordinator.jsp
  src/main/webapp/css/board.css
  src/main/webapp/css/bottom.css
  src/main/webapp/css/home.css
  src/main/webapp/css/top.css
Labels: enhancement

#159 코디네이터 리스트, 코디네이터 등록(관리자) 뷰 연결
  src/main/java/com/team/bf/controller/AdminController.java
  src/main/java/com/team/bf/controller/CoordinatorController.java
  src/main/java/com/team/bf/dao/CoordinatorDAO.java
  src/main/java/com/team/bf/service/CoordinatorService.java
  src/main/java/com/team/bf/service/CoordinatorServiceImpl.java
  src/main/resources/mapper/coordinatorMapper.xml
  src/main/webapp/WEB-INF/views/coordinator/coordinator.jsp
  src/main/webapp/WEB-INF/views/coordinator/coordinatorForm.jsp
Labels: enhancement

#162 [FEAT] admin 회원관리 기능 추가, detailCommon 좌표값 추가
  src/main/java/com/team/bf/controller/AccommodationController.java
  src/main/java/com/team/bf/service/OpenApiService.java
  src/main/resources/application.yml
  src/main/webapp/WEB-INF/views/admin/memberList.jsp
Labels: enhancement

#166 Feature/admin view
  src/main/webapp/WEB-INF/views/coordinator/coordinator.jsp
  src/main/webapp/WEB-INF/views/coordinator/coordinatorForm.jsp
  src/main/webapp/css/bottom.css
  src/main/webapp/css/introductionstyle.css
  src/main/webapp/img/introduction/introimg4.jpg
Labels: enhancement

#167 [FEAT]plan 리스트 레이아웃 수정, 리스트 DB 저장 구현
  src/main/webapp/WEB-INF/views/map/mapView.jsp
  src/main/webapp/css/mapstyle.css
Labels: enhancement

#171 MapAndPlannerController 여행계획 1개 데이터 불러오기 기능 추가
  src/main/java/com/team/bf/controller/MapAndPlannerController.java
Labels: enhancement

#173 [FEAT]plan 리스트추가 기능수정, plan 불러오기 기능구현
  src/main/webapp/WEB-INF/views/map/mapView.jsp
  src/main/webapp/css/mapstyle.css
Labels: enhancement

#175 나의 문의사항에서 모든 문의사항 보이는 거 수정
  src/main/java/com/team/bf/controller/MapAndPlannerController.java
  src/main/java/com/team/bf/controller/ReviewController.java
  src/main/resources/mapper/boardMapper.xml
  src/main/webapp/WEB-INF/views/mypage/myplan.jsp
Labels: bug

#180 [FEAT]코디네이터 등록및 리스트 뷰
  src/main/java/com/team/bf/controller/CoordinatorController.java
  src/main/webapp/WEB-INF/inc/top.jsp
  src/main/webapp/WEB-INF/views/admin/coordinator.jsp
  src/main/webapp/WEB-INF/views/coordinator/coordinator.jsp
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/img/coordinator/cyj.png
  src/main/webapp/img/coordinator/kch.png
  src/main/webapp/img/coordinator/kdi.png
  src/main/webapp/img/coordinator/kdw.png
  src/main/webapp/img/coordinator/kmh.png
  src/main/webapp/img/coordinator/sjh.png
Labels: enhancement

#183 [FEAT]plan 로그인 시에서만 플래너리스트 뜨게 수정
  src/main/webapp/WEB-INF/views/map/mapView.jsp
  src/main/webapp/css/mapstyle.css
  src/main/webapp/img/map/map_31.png
  src/main/webapp/img/map/map_32.png
  src/main/webapp/img/map/map_33.png
  src/main/webapp/img/map/map_34.png
Labels: enhancement

#184 [FEAT] boardcontroller, cordinator 수정
  src/main/java/com/team/bf/controller/BoardController.java
  src/main/java/com/team/bf/controller/CoordinatorController.java
  src/main/webapp/WEB-INF/views/admin/coordinatorForm.jsp
  src/main/webapp/WEB-INF/views/community/boardEdit.jsp
  src/main/webapp/WEB-INF/views/coordinator/coordinatorForm.jsp
Labels: enhancement

#187 마이페이지에서->지도 여행 계획 불러오기 기능 추가
  src/main/webapp/WEB-INF/views/mypage/myplan.jsp
Labels: enhancement

#188 관리자 문의/게시글 관리 뷰 수정
  src/main/webapp/WEB-INF/views/admin/board.jsp
  src/main/webapp/WEB-INF/views/admin/boardFormReply.jsp
  src/main/webapp/WEB-INF/views/community/boardDetail.jsp
Labels: enhancement

#190 [FEAT]메인페이지 숙소 별점 추가
  src/main/webapp/WEB-INF/views/home.jsp
Labels: enhancement

#191 상세페이지 별점 기능 버그 수정
  src/main/webapp/WEB-INF/views/accommodation/accommodationView.jsp
  src/main/webapp/WEB-INF/views/travel_information/travel_informationView.jsp
Labels: bug

#194 [FEAT]모달 레이아웃 구현중
  src/main/webapp/WEB-INF/views/map/mapView.jsp
  src/main/webapp/css/mapstyle.css
Labels: enhancement

#196 교통수단페이지
  src/main/webapp/WEB-INF/views/transportation/bus.jsp
  src/main/webapp/WEB-INF/views/transportation/plane.jsp
  src/main/webapp/WEB-INF/views/transportation/taxi.jsp
  src/main/webapp/WEB-INF/views/transportation/transportationView.jsp
  src/main/webapp/css/introductionstyle.css
  src/main/webapp/css/transportationView.css
Labels: enhancement

#199 [FEAT]discount뷰 구현, 동행자 추가삭제 기능구현
  src/main/java/com/team/bf/controller/DiscountController.java
  src/main/webapp/WEB-INF/views/discount/discountDetailView.jsp
  src/main/webapp/WEB-INF/views/map/mapView.jsp
  src/main/webapp/css/mapstyle.css
  src/main/webapp/img/discount/discount.png
Labels: enhancement

#201 [FIX]로그아웃 상태일때 리스트 추가 뜨는 것 수정
  src/main/webapp/WEB-INF/views/map/mapView.jsp
  src/main/webapp/css/mapstyle.css
Labels: bug

#202 [FEAT]top.jsp 관리자 수정
  src/main/webapp/WEB-INF/inc/top.jsp
Labels: enhancement

#203 [FIX] 리스트 배경 겹치는 것 수정
  src/main/webapp/WEB-INF/views/map/mapView.jsp
  src/main/webapp/css/mapstyle.css
Labels: bug

#207 별점 표시 수정
  src/main/webapp/WEB-INF/views/accommodation/accommodationPage.jsp
  src/main/webapp/WEB-INF/views/travel_information/travel_informationPage.jsp
Labels: bug
